version: '3.8'

services:
  web:
    container_name: web
    image: app4
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DATABASE: urukundo
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: urukundo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
